name = "Bleeding"
icon = "dummy"
duration = "Rest"
on_debuff = '''
local stats = require "esprit.types.stats"

local debuff, magnitude = 0, ...
while magnitude > (debuff + 1) * 10 do
	magnitude = magnitude - (debuff + 1) * 10;
	debuff = debuff + 1;
end

return stats.defense(debuff)
'''
