name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt-get install -yq libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libluajit-5.1-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
