name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install SDL 2
      run: apt install sdl2
    - name: Install LuaJIT
      run: apt install luajit
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
